### ISSUE TITLE
Increase the hight of the iframe to include the tools below the player

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-filter_opencast#12]
Currently, there is a vertical scroll bar. This is not very nice.
![image](https://user-images.githubusercontent.com/9437254/38499066-bf7d5c9e-3c06-11e8-8c54-6d1a2c9ea857.png)

**Comment by TamaraGunkel** [comment]
This will not longer happen if the Paella Player is used.
