### ISSUE TITLE
Horizontally scaling the player

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-filter_opencast#13]
Moodle is able to indent activities and therefor for instance labels. This way the iframe has fewer space to display its content. Is there a pay to automatically scale the content to prevent a horizontal scrolling bar?
![image](https://user-images.githubusercontent.com/9437254/38499138-f2512f24-3c06-11e8-9acd-8c8c350d8d22.png)

**Comment by TamaraGunkel** [comment]
This is not longer relevant because the Paella player will be used. The Paella player automatically resizes itself.
