### ISSUE TITLE
The 'custom_tool' parameter was invalid: 'null'.

### ISSUE THREAD

**Issue by loewis** [Opencast-Moodle/moodle-filter_opencast#17]
The filter currently triggers an error message in the opencast log:

    2018-09-06 18:02:22,679 | WARN  | (LtiServlet:221) - The 'custom_tool' parameter was invalid: 'null'. Reverting to default: '/ltitools'

The source of the problem is that the filter's LTI launch to obtain the cookie does not specify a tool. To suppress the error message, "custom_tool=/ltitools" should be added to the parameters.

**Comment by ghost** [comment]
In which file I must write custom_tool=/ltitools??
I can´t find it.

**Comment by NinaHerrmann** [comment]
This was added https://github.com/Opencast-Moodle/moodle-filter_opencast/blob/46a8aa1a417fd8079bd95ef7876182c2f613299b/lib.php#L95 Requires testing for release candidate.
