### ISSUE TITLE
Handling of already logged in state

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-filter_opencast#5]
We have to think about the check for existing cookies here. 
This could be problematic, if opencast and moodle run on different servers.

https://github.com/TamaraGunkel/moodle-filter_opencastfilter/blob/abed94061cd2042d0814606e01f7d766ef522456/filter.php#L57

**Comment by TamaraGunkel** [comment]
Is this issue still relevant?
It should be irrelevant if opencast and moodle run on different servers because the cookies are saved in the browser, shouldn't it?

**Comment by loewis** [comment]
I think the test for the existing cookie should be dropped. If Opencast runs on a separate server, the browser will refuse to the send the cookie to Moodle, so you cannot check whether the cookie is set, anyway. If they run on the same server, it might be worse: the session might be expired even though the cookie is still present. I can't see a problem with logging in every time the page is rendered.

**Comment by NinaHerrmann** [comment]
Will be dropped due to previous arguments, and no complaints.
