### ISSUE TITLE
Rethink  opencast login

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-filter_opencast#6]
Currently, I have to guess what the function filter_opencast_login is actually doing. Optimally, the function name directly represents what the function is doing. In the end, the function does something in between of executing the login and rendering the automatic login form. Maybe you can split up the responsibilities there. The creation of the automatic login form should again be done using a renderer function.

https://github.com/TamaraGunkel/moodle-filter_opencastfilter/blob/abed94061cd2042d0814606e01f7d766ef522456/filter.php#L59

**Comment by TamaraGunkel** [comment]
I have changed this in 7b364303df31b77e5b59e606f052cd65e262aaff
